name: Sync with GitLab

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Secret
        run: echo "GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab.com/nourhen-jbali/hotelreservation
          GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }} git push gitlab main
